export const CHANGE_MAIN_HEADER = "CHANGE_MAIN_HEADER";
export const CHANGE_MAIN_SUBHEADER = "CHANGE_MAIN_SUBHEADER";
export const CHANGE_MAIN_BANNER = "CHANGE_MAIN_BANNER";
export const RESET_MAIN = "RESET_MAIN";

export const CHANGE_ARTICLES_LIST = "CHANGE_ARTICLES_LIST";

export const CHANGE_FIRST_NAME = "CHANGE_FIRST_NAME";
export const CHANGE_SECOND_NAME = "CHANGE_SECOND_NAME";
export const CHANGE_THIRD_NAME = "CHANGE_THIRD_NAME";

export const CHANGE_FIRST_LINK = "CHANGE_FIRST_LINK";
export const CHANGE_SECOND_LINK = "CHANGE_SECOND_LINK";
export const CHANGE_THIRD_LINK = "CHANGE_THIRD_LINK";
